"""add_question_evaluations_jsonb_column

Revision ID: 178dba9c9f99
Revises: b8a59747f90f
Create Date: 2026-08-14 21:58:15.323323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '178dba9c9f99'
down_revision: Union[str, Sequence[str], None] = 'b8a59747f90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_evaluations')
    op.drop_table('answers')
    op.alter_column('interview_evaluations', 'question_evaluations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_evaluations', 'question_evaluations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.create_table('question_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_evaluation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('question_evaluations_answer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_evaluation_id'], ['interview_evaluations.id'], name=op.f('question_evaluations_interview_evaluation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('question_evaluations_pkey')),
    sa.UniqueConstraint('answer_id', name=op.f('question_evaluations_answer_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('answers_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('answers_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('answers_pkey'))
    )
    # ### end Alembic commands ###
