"""add_organization_model_and_multi_tenancy

Revision ID: d7b6a0fd0e48
Revises: ca242a19e080
Create Date: 2026-08-15 23:57:44.875371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b6a0fd0e48'
down_revision: Union[str, Sequence[str], None] = 'ca242a19e080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.alter_column('interviews', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # DATA MIGRATION: Create default orgs and assign users/interviews
    bind = op.get_bind()
    
    # Reset existing garbage data to avoid FK violations
    bind.execute(sa.text("UPDATE users SET organization_id = NULL"))
    bind.execute(sa.text("UPDATE interviews SET organization_id = NULL"))

    # Fetch all admins who have completed onboarding
    admins = bind.execute(sa.text("SELECT id, name FROM users WHERE role='admin' AND is_onboarded=true")).fetchall()
    
    for admin in admins:
        # Create an organization using the admin's overloaded name
        org_name = f"{admin.name} Organization" if admin.name else "Default Organization"
        org_result = bind.execute(
            sa.text("INSERT INTO organizations (name) VALUES (:name) RETURNING id"),
            {"name": org_name}
        ).fetchone()
        org_id = org_result[0]
        
        # Link the admin to this org
        bind.execute(
            sa.text("UPDATE users SET organization_id = :org_id WHERE id = :user_id"),
            {"org_id": org_id, "user_id": admin.id}
        )
        # Link all interviews created by this admin to this org
        bind.execute(
            sa.text("UPDATE interviews SET organization_id = :org_id WHERE created_by = :user_id"),
            {"org_id": org_id, "user_id": admin.id}
        )

    op.drop_index(op.f('ix_interviews_organization_id'), table_name='interviews')
    op.create_foreign_key(None, 'interviews', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_index(op.f('ix_interviews_organization_id'), 'interviews', ['organization_id'], unique=False)
    op.alter_column('interviews', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
