"""add organization indexes

Revision ID: 9835dadda319
Revises: d7b6a0fd0e48
Create Date: 2026-08-16 22:52:32.393170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9835dadda319'
down_revision: Union[str, Sequence[str], None] = 'd7b6a0fd0e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interviews_organization_id'), 'interviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_interviews_organization_id'), table_name='interviews')
    # ### end Alembic commands ###
