"""add organization join links

Revision ID: 413b423984bf
Revises: 6368dc080488
Create Date: 2026-08-18 22:24:31.483716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413b423984bf'
down_revision: Union[str, Sequence[str], None] = '6368dc080488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_join_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_join_links_id'), 'organization_join_links', ['id'], unique=False)
    op.create_index(op.f('ix_organization_join_links_organization_id'), 'organization_join_links', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_join_links_token_hash'), 'organization_join_links', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_join_links_token_hash'), table_name='organization_join_links')
    op.drop_index(op.f('ix_organization_join_links_organization_id'), table_name='organization_join_links')
    op.drop_index(op.f('ix_organization_join_links_id'), table_name='organization_join_links')
    op.drop_table('organization_join_links')
    # ### end Alembic commands ###
