"""add_is_onboarded_column_to_users

Revision ID: ca242a19e080
Revises: 178dba9c9f99
Create Date: 2026-08-15 14:33:28.099512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca242a19e080'
down_revision: Union[str, Sequence[str], None] = '178dba9c9f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(),server_default=sa.text('false') ,nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_onboarded')
    # ### end Alembic commands ###
